# hwr64/configs/datasets.yaml
# Root download folder; agent may override via CLI
root: hwr64/data/raw

# Global options
options:
  retries: 3
  timeout_sec: 1800
  user_agent: "hwr64-fetch/1.0"

# Datasets
datasets:
  # ---- Latin & digits ----
  - name: mnist
    method: http
    dest: mnist
    files:
      - url: https://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz
        sha256: null
      - url: https://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz
        sha256: null
      - url: https://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz
        sha256: null
      - url: https://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz
        sha256: null

  - name: emnist
    method: kaggle
    dest: emnist
    kaggle:
      # Requires Kaggle CLI with credentials
      dataset: crawford/emnist
      # Optional: limit specific files, else downloads all
      files: []

  - name: nist_sd19
    method: http
    dest: nist_sd19
    files:
      - url: https://s3.amazonaws.com/nist-srd/SD19/by_class.zip
        sha256: null
    postprocess:
      - unzip: by_class.zip

  # ---- Math/Latin/Greek symbols ----
  - name: hasyv2
    method: kaggle
    dest: hasyv2
    kaggle:
      dataset: martinthoma/hasyv2-dataset-friend-of-mnist
      files: []

  # ---- Japanese (Kuzushiji) ----
  - name: kmnist
    method: http
    dest: kmnist
    files:
      - url: https://codh.rois.ac.jp/kmnist/dataset/kmnist/train-images-idx3-ubyte.gz
      - url: https://codh.rois.ac.jp/kmnist/dataset/kmnist/train-labels-idx1-ubyte.gz
      - url: https://codh.rois.ac.jp/kmnist/dataset/kmnist/t10k-images-idx3-ubyte.gz
      - url: https://codh.rois.ac.jp/kmnist/dataset/kmnist/t10k-labels-idx1-ubyte.gz

  - name: k49
    method: http
    dest: k49
    files:
      - url: https://codh.rois.ac.jp/kmnist/dataset/k49/k49-train-imgs.npz
      - url: https://codh.rois.ac.jp/kmnist/dataset/k49/k49-train-labels.npz
      - url: https://codh.rois.ac.jp/kmnist/dataset/k49/k49-test-imgs.npz
      - url: https://codh.rois.ac.jp/kmnist/dataset/k49/k49-test-labels.npz

  - name: kuzushiji_kanji
    method: http
    dest: kuzushiji_kanji
    files:
      - url: https://codh.rois.ac.jp/kmnist/dataset/kkanji/kkanji.tar
    postprocess:
      - tar_extract: kkanji.tar

  # ---- Omniglot ----
  - name: omniglot
    method: http
    dest: omniglot
    files:
      - url: https://github.com/brendenlake/omniglot/raw/master/python/images_background.zip
      - url: https://github.com/brendenlake/omniglot/raw/master/python/images_evaluation.zip
      - url: https://github.com/brendenlake/omniglot/raw/master/python/strokes_background.zip
      - url: https://github.com/brendenlake/omniglot/raw/master/python/strokes_evaluation.zip
    postprocess:
      - unzip: images_background.zip
      - unzip: images_evaluation.zip

  # ---- Arabic ----
  - name: madbase_digits
    method: kaggle
    dest: madbase_digits
    kaggle:
      dataset: hossamahmedsalah/arabicindian-digits-madbase
      files: []

  - name: ahcd_characters
    method: kaggle
    dest: ahcd_characters
    kaggle:
      dataset: mloey1/ahcd1
      files: []

  # ---- Devanagari ----
  - name: devanagari_chars
    method: kaggle
    dest: devanagari_chars
    kaggle:
      dataset: ashokpant/devanagari-character-dataset
      files: []

  # ---- Chinese (CASIA) & IAM (manual) ----
  - name: casia_hwdb
    method: manual
    dest: casia_hwdb
    instructions: |
      CASIA HWDB/OLHWDB require registration and agreement at NLPR (CASIA) site. After approval, place downloaded archives here and re-run the fetcher with --verify to index.
      Portal: https://nlpr.ia.ac.cn/databases/handwriting/home.html

  - name: iam_db
    method: manual
    dest: iam_db
    instructions: |
      IAM Handwriting Database requires registration. After access is granted, download the datasets and place them here. Then run the indexing script under scripts to convert to 64x64 crops or line images as needed.
      Portal: https://fki.tic.heia-fr.ch/databases/iam-handwriting-database
